# workflow 이름
# 1 workflow = 1 yml
name: Github Actions 실행시키기

# event : 실행되는 시점 - main
on:
  push:
    branches:
      - main

# 1개 이상의 job으로 구성 (병렬)
jobs:
  # job id
  My-Deploy-Job:
    # 실행시킬 서버
    runs-on: ubuntu-latest

    #step: 작업을 수행할 가장 작은 단위
    steps:
      - name: ssh 원격 접속
        # library 사용
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script_stop: true
          script: |
            cd /home/cicd
            git pull origin main
            ./gradlew clean build      
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
