# workflow 이름
# 1 workflow = 1 yml
name: Github Actions 실행시키기

# event : 실행되는 시점 - main
on:
  push:
    branches:
      - main

# 1개 이상의 job으로 구성 (병렬)
jobs:
  # job id
  My-Deploy-Job:
    # 실행시킬 서버
    runs-on: ubuntu-latest

    #step: 작업을 수행할 가장 작은 단위
    steps:
      - name: Hello world 찍기
        run: echo "hello world"

      - name: 여러 명령어 문장 작성
        run: |
          echo "Good"
          echo "Morning"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: 아무한테 노출되면 안되는 값
        run: echo ${{secrets.MY_NAME}} #세팅에 정의
